name: Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - ".editorconfig"
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64]
        configuration: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Add MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Install dependencies for editor
    - name: Setup vcpkg
      run: |
        vcpkg install raylib:x64-windows-static
        vcpkg install raygui:x64-windows-static
        vcpkg integrate install

    # Build solution
    - name: Build Solution
      run: msbuild $env:Solution_Name /t:build /p:configuration=${{ matrix.configuration }}
